export const consoleEndpoints = {
  status: '/api/status',
  agentSessions: '/api/agent/sessions',
  agentSession: (id: string) => `/api/agent/sessions/${encodeURIComponent(id)}`,
  agentChat: '/api/agent/chat',
  agentChatHistory: (sessionId: string) => `/api/agent/chat/history?limit=40&session_id=${encodeURIComponent(sessionId)}`,
  agentStop: (id: string) => `/api/agent/stop/${encodeURIComponent(id)}`,
  agentsFleet: '/api/agents/fleet',
  specialistAgentChat: (id: string) => `/api/agents/${encodeURIComponent(id)}/chat`,
  automationsStatus: '/api/automations/status',
  integrationsStatus: '/api/integrations/status',
  integrationsAuthorize: '/api/integrations/authorize',
  googleImport: '/api/google/import',
  googleImportStatus: '/api/google/import/status',
  flags: '/api/flags',
  testsProfiles: '/api/tests/profiles',
  testsStatus: '/api/tests/status',
  testsRun: '/api/tests/run',
  testsCancel: '/api/tests/cancel',
  testsSummarize: '/api/tests/summarize',
  reportsLatest: '/api/test-reports/latest',
  reportsHistory: '/api/test-reports/history?limit=180',
  reportByFile: (file: string) => `/api/test-report/by-file?file=${encodeURIComponent(file)}`,
  systemAgentSessionRef: (agentId: string) => `agent:${agentId}:main:web:fleet-${agentId}@${agentId}`,
}
